app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/recipes
      username: recipes
      password: 'password'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  datasource:
      url: jdbc:postgresql://localhost:5332/recipes
      username: amigoscode
      password: password


