package com.laszlo.recipes.model;

import com.sun.istack.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import java.util.ArrayList;
import java.util.List;

/**
 * An ingredient has relationship with a {@link Recipe} wherein a recipe can have multiple ingredients where they can either be included or excluded.
 */
@Entity
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Ingredient {

    /**
     * Id generated by postgres with a sequence table.
     */
    @Id
    @SequenceGenerator(name="pk_sequence",sequenceName="recipe_seq", allocationSize=1)
    @GeneratedValue(strategy= GenerationType.SEQUENCE,generator="pk_sequence")
    private Integer id;

    /**
     * The name of the ingredient.
     */
    private String name;

    /**
     * Where or not the ingredient is in the meal.
     */
    private Inclusion inclusion;

    /**
     * References a {@link Recipe}
     */
    @ManyToOne(optional = true)
    @JoinColumn(name = "recipe_id")
    private Recipe recipe;

    public enum Inclusion {
        INCLUDED,
        EXCLUDED
    }
}
